#
# (c) Copyright 2021 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  auth-setup:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-auth-setup${ISOL_DOCKER_VERSION_SEP}${ISOL_VERSION}
    networks:
      - main
    environment:
      - ISOL_AUTH_SERVICE_PROTOCOL=${ISOL_AUTH_SERVICE_PROTOCOL}
      - ISOL_AUTH_SERVICE_HOST=${ISOL_AUTH_SERVICE_HOST}
      - ISOL_AUTH_SERVICE_PORT=${ISOL_AUTH_SERVICE_PORT}
      - ISOL_AUTH_SERVICE_PATH=${ISOL_AUTH_SERVICE_PATH}
      - ISOL_AUTH_SERVICE_ADMIN_USER=${ISOL_AUTH_SERVICE_ADMIN_USERNAME}
      - ISOL_AUTH_SERVICE_ADMIN_PASS=${ISOL_AUTH_SERVICE_ADMIN_PASSWORD}
      - ISOL_AUTH_SERVICE_REALM=${ISOL_AUTH_SERVICE_REALM}
      - ISOL_AUTH_SERVICE_API_CLIENT=${ISOL_AUTH_SERVICE_API_CLIENT}
      - ISOL_AUTH_SERVICE_API_CLIENT_SECRET=${ISOL_AUTH_SERVICE_API_CLIENT_SECRET}
      - ISOL_AUTH_SERVICE_API_URL=${ISOL_EXTERNAL_PROTOCOL}://${ISOL_API_SERVICE_EXTERNAL_HOST}:${ISOL_API_SERVICE_EXTERNAL_PORT}${ISOL_API_SERVICE_EXTERNAL_PATH}
      - ISOL_AUTH_SERVICE_UI_CLIENT=${ISOL_AUTH_SERVICE_UI_CLIENT}
      - ISOL_AUTH_SERVICE_UI_URL=${ISOL_EXTERNAL_PROTOCOL}://${LEMA_UI_EXTERNAL_HOST}:${LEMA_UI_EXTERNAL_PORT}${LEMA_UI_EXTERNAL_PATH}
