#
# (c) Copyright 2021 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  auth-db:
    image: postgres:${ISOL_POSTGRES_VERSION}
    networks:
      - main
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - ${ISOL_AUTH_DB_DOCKER_PORT}:5432
    environment:
      POSTGRES_USER: ${ISOL_AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${ISOL_AUTH_DB_PASSWORD}
      POSTGRES_DB: ${ISOL_AUTH_DB_NAME}

  auth-service:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-auth-service${ISOL_DOCKER_VERSION_SEP}${ISOL_VERSION}
    depends_on:
      - auth-db
    networks:
      - main
    volumes:
      - ${ISOL_AUTH_SERVICE_TLS_CERT_DIR}:/etc/x509/https
    ports:
      - ${ISOL_AUTH_SERVICE_DOCKER_PORT}:${ISOL_AUTH_SERVICE_INTERNAL_PORT}
    environment:
      - KEYCLOAK_USER=${ISOL_AUTH_SERVICE_ADMIN_USERNAME}
      - KEYCLOAK_PASSWORD=${ISOL_AUTH_SERVICE_ADMIN_PASSWORD}
      - DB_VENDOR=POSTGRES
      - DB_ADDR=auth-db
      - DB_USER=${ISOL_AUTH_DB_USERNAME}
      - DB_PASSWORD=${ISOL_AUTH_DB_PASSWORD}
      - DB_DATABASE=${ISOL_AUTH_DB_NAME}
      - DB_SCHEMA=public
      - KEYCLOAK_FRONTEND_URL=${ISOL_EXTERNAL_PROTOCOL}://${ISOL_AUTH_SERVICE_EXTERNAL_HOST}:${ISOL_AUTH_SERVICE_EXTERNAL_PORT}${ISOL_AUTH_SERVICE_EXTERNAL_PATH}
      - ISOL_AUTH_DB_HOST=auth-db

volumes:
  auth-db-data:
